### PR TITLE
fix (offset - 1) pagination

### LINKED ISSUE #409: pagination problems
> the “Next” link at the bottom of [this page](https://staging.thegraph.com/docs/en/substreams/getting-started/quickstart/) goes to the wrong page (“Dependency installation”; it skips “Overview”, which is the actual next page).

> Huh, and on the [Dependency installation](https://staging.thegraph.com/docs/en/substreams/developers-guide/installation-requirements/) page, the “Previous” link goes to… the current page. And the “Next” link skips another page, too. (edited)

### PR DESCRIPTION
**Pull request by dimaMachina**
fixes https://github.com/graphprotocol/docs/issues/409

### CODE REVIEW

File: website/pages/en/_meta.js [hunk 1]
```diff
@@ -7,7 +7,6 @@ export default {
   network: 'The Graph Network',
   sunrise: 'Sunrise FAQ',
   billing: '',
-  'network-transition-faq': '',
```
Comment (dimaMachina) [inline website/pages/en/_meta.js:10]: this hidden route produced offset - 1 issue since, I used `flatDirectories` list instead of `flatDocsDirectories`

because in original `nextra-theme-docs` were props naming confusing

https://github.com/shuding/nextra/blob/2f001d897f2109b24600f66fe2009e5f788b980c/packages/nextra-theme-docs/src/components/nav-links.tsx#L22
https://github.com/shuding/nextra/blob/2f001d897f2109b24600f66fe2009e5f788b980c/packages/nextra-theme-docs/src/index.tsx#L220

File: website/pages/en/quick-start.mdx [hunk 2]
```diff
@@ -67,9 +67,9 @@ See the following screenshot for an example for what to expect when initializing
 
 The previous commands create a scaffold subgraph that you can use as a starting point for building your subgraph. When making changes to the subgraph, you will mainly work with three files:
 
-- Manifest (subgraph.yaml) - The manifest defines what datasources your subgraphs will index.
-- Schema (schema.graphql) - The GraphQL schema defines what data you wish to retrieve from the subgraph.
-- AssemblyScript Mappings (mapping.ts) - This is the code that translates data from your datasources to the entities defined in the schema.
```
Comment (dimaMachina) [inline website/pages/en/quick-start.mdx:72]: just better to use inline code blocks for filenames

File: website/pages/en/quick-start.mdx [hunk 3]
```diff
@@ -67,9 +67,9 @@ See the following screenshot for an example for what to expect when initializing
...
+- Manifest (`subgraph.yaml`) - The manifest defines what datasources your subgraphs will index.
+- Schema (`schema.graphql`) - The GraphQL schema defines what data you wish to retrieve from the subgraph.
+- AssemblyScript Mappings (`mapping.ts`) - This is the code that translates data from your datasources to the entities defined in the schema.
```
Comment (dimaMachina) [inline website/pages/en/quick-start.mdx:72]: just better to use inline code blocks for filenames

**Review by saihaj — APPROVED** [review]

File: website/pages/en/_meta.js (hunk 1 above)
Comment (benface) [reply website/pages/en/_meta.js:10]: Really nice catch!
