### PR TITLE
Update dependencies + fix typecheck

### LINKED ISSUE #417: fix typechek for nextra-theme
https://github.com/graphprotocol/docs/pull/407#issuecomment-1582724619

https://github.com/graphprotocol/docs/blob/160941e245b5dd13f29ead0cc4518ea82e282b52/packages/nextra-theme/package.json#L23

### PR DESCRIPTION
**Pull request by benface**
Fixes #417

### CODE REVIEW

File: packages/nextra-theme/src/layout/MDXLayoutNav.tsx [hunk 1]
```diff
@@ -58,7 +58,7 @@ const DesktopWrapper = ({ children }: PropsWithChildren<{}>) => {
 
 const MobileWrapper = ({ title, children }: PropsWithChildren<{ title?: string }>) => {
   const [open, setOpen] = useState(false)
-  const { t } = useI18n()
+  const { t } = useI18n<any>()
```
Comment (benface) [inline packages/nextra-theme/src/layout/MDXLayoutNav.tsx:61]: Adding `any` is obviously not a great fix, but it's how `useI18n` is currently used [elsewhere in `nextra-theme`](https://github.com/graphprotocol/docs/blob/main/packages/nextra-theme/src/components/EditPageLink.tsx#L23). I still don't fully understand the point of extracting the theme to a separate package if I'm being completely honest; we wouldn't need to use `any` if this was in the `website` package because the translations live there.

Comment (B2o5T) [reply packages/nextra-theme/src/layout/MDXLayoutNav.tsx:61]: We extracted it to be possible to install the same theme in another repository? We can back nextra-theme in the `website` folder if it is no longer the case with remote mdx cc @saihaj

**Comment by benface** [comment]
@B2o5T @saihaj @dotansimha – Do you guys have any idea why the CI is failing with the following error and what we can do about it? I'm able to build the app just fine locally.

```
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xb7a940 node::Abort() [node]
   2: 0xa8e823  [node]
   3: 0xd5c990 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
   4: 0xd5cd37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
   5: 0xf3a435  [node]
   6: 0xf3b338 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
   7: 0xf4b843  [node]
   8: 0xf4c6b8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
   9: 0xf2701e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
  10: 0xf283e7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
  11: 0xf095ba v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
  12: 0x12ce7ff v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
  13: 0x16fb6f9  [node]
  Aborted (core dumped)
   ELIFECYCLE  Command failed with exit code 134.
```

**Comment by B2o5T** [comment]
@benface don’t know maybe related to updating some dependency

**Comment by benface** [comment]
> maybe related to updating some dependency

@B2o5T – Could be, but I don't think so because this other PR also just got the same error: https://github.com/graphprotocol/docs/actions/runs/5535418204/jobs/10101686588

**Comment by benface** [comment]
OK, fixed the CI error by allowing Node to use more memory. 🥲

**Comment by benface** [comment]
@B2o5T @saihaj – This PR is now ready to be reviewed. :)

File: .github/workflows/next-js-bundle-analysis.yml [hunk 2]
```diff
@@ -46,7 +46,7 @@ jobs:
 
       - name: Build Next.js App
         # change this if your site requires a custom build command
-        run: cd .. && pnpm build
+        run: cd .. && export NODE_OPTIONS="--max_old_space_size=4096" && pnpm build
```
Comment (B2o5T) [inline .github/workflows/next-js-bundle-analysis.yml:49]:
```suggestion
        run: cd .. && NODE_OPTIONS="--max_old_space_size=4096" pnpm build
```

Comment (benface) [reply .github/workflows/next-js-bundle-analysis.yml]: Good call, done in https://github.com/graphprotocol/docs/pull/437/commits/9391487863039f405b77eeba799550c40fd587c3
